### ISSUE TITLE
forestry compatibility

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [ezterry/ezwasteland#3]
Is it possible to have bee hives spawn normally? forge events yes don't seem to matter

Also forestry green house make world gen crashing only in combination with ezwasteland, if I turn normal worldgen on everything generate normally, when I turn ezwasteland on world gen crashes and hang my computer. Could it be an issue on their side?

Thank you for your time.

**Comment by ezterry** [comment]
Regarding hives I'm not sure how forestry spawns then, I assume it's looking for specific conditions and not finding them.  (Since there is no dirt, grass, Stone, tree, or logs in the world)
I'd recommend using recurrent complex or other structure mod to define some (admittedly very small) structures to spawn the hives you want at the frequency you want. Its possible something else would be possible but obviously the alternative spawn conditions would need to be considered.

The greenhouse however I'll need to check the log to be sure but you didn't find a bug on my side but the wastelands ought not cause the crash, regardless send a crash log and I'll look into it more.

**Comment by Ganjalf-Amsterdoom** [comment]
Thank for the reply, I will look into cohf-world to spawn the hives, as for the log i'll send it asap.

**Comment by ezterry** [comment]
close for now unless more information is provided
